### ISSUE TITLE
Name sync

### ISSUE THREAD

**Issue by owenselles** [Chickenpowerrr/RankSync#4]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I would like a function to sync names from Minecraft to Discord and set discord names to ingame names automatically.

**Describe alternatives you've considered**
wasn't able to find any.

**Additional context**
-

**Comment by Chickenpowerrr** [comment]
Hello Owen, 

since the name of this plugin is RankSync its core job is to synchronize ranks.
Right now I can add to the todo list, but it will get a low priority since there are a lot more important features that should get added before this feature (like BungeeCord support).

Thanks for thinking along!

**Comment by Chickenpowerrr** [comment]
Hello Owner,

in the 1.3.0 update the Name Sync feature has been added.
You can download the version [here](https://www.spigotmc.org/resources/ranksync.61393/)
You need to add the _sync-names: true_ line to your config.yml like [this](https://github.com/Chickenpowerrr/RankSync/blob/e56cfc8181395e8b11f4670667951802b2ff985a/server/src/main/resources/config.yml#L9).

**Comment by owenselles** [comment]
ah nice thanks!
